version: '3'

services:
    db:
      container_name: mysql_80
      image: mysql/mysql-server:8.0
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=Admin123
        - MYSQL_ROOT_HOST=172.%    # Allow docker contatiners to connect to mysql
      command: --max_allowed_packet=4G
      ports:
        - 3308:3306
      healthcheck:
        test: "exit 0"
      platform:  "linux/amd64"
      volumes:
        - ./data:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

volumes:
  data:
